apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    sandbox: learn-kubernetes
    learn-kubernetes: quotemysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306